<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class DivisionalSecretariatOffices extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('divisional_secretariat_offices')->insert([
            array("dso_id"=>"DSO0001","dso_name"=>"Vavuniya North","district_id"=>"DIS010",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0002","dso_name"=>"Vavuniya","district_id"=>"DIS010",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0003","dso_name"=>"Vavuniya South","district_id"=>"DIS010",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0004","dso_name"=>"Vengalacheddiculam","district_id"=>"DIS010",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0005","dso_name"=>"Kuchaveli","district_id"=>"DIS004",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0006","dso_name"=>"Gomarankadawela","district_id"=>"DIS004",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0007","dso_name"=>"Morawewa","district_id"=>"DIS004",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0008","dso_name"=>"Town & Gravets","district_id"=>"DIS004",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0009","dso_name"=>"Kinniya","district_id"=>"DIS004",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0010","dso_name"=>"Thampalakamam","district_id"=>"DIS004",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0011","dso_name"=>"Muttur","district_id"=>"DIS004",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0012","dso_name"=>"Kantalai","district_id"=>"DIS004",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0013","dso_name"=>"Seruvila","district_id"=>"DIS004",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0014","dso_name"=>"Eachchilampattai","district_id"=>"DIS004",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0015","dso_name"=>"Padavi Sri Pura","district_id"=>"DIS004",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0016","dso_name"=>"Kolonna","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0017","dso_name"=>"Embilipitiya","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0018","dso_name"=>"Weligepola","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0019","dso_name"=>"Kalawana","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0020","dso_name"=>"Nivithigala","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0021","dso_name"=>"Rathnapura","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0022","dso_name"=>"Pelmadulla","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0023","dso_name"=>"Opanayaka","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0024","dso_name"=>"Kuruwita","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0025","dso_name"=>"Kiriella","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0026","dso_name"=>"Kahawaththa","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0027","dso_name"=>"Imbulpe","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0028","dso_name"=>"Godakawela","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0029","dso_name"=>"Elapatha","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0030","dso_name"=>"Eheliyagoda","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0031","dso_name"=>"Ayagama","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0032","dso_name"=>"Balangoda","district_id"=>"DIS015",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0033","dso_name"=>"Nattandiya","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0034","dso_name"=>"Vanathavilluwa","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0035","dso_name"=>"Kalpitiya","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0036","dso_name"=>"Mundalama","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0037","dso_name"=>"Mahakumbukkadawala","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0038","dso_name"=>"Anamaduwa","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0039","dso_name"=>"Wennappuwa","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0040","dso_name"=>"Puttalam","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0041","dso_name"=>"Karuwalagaswewa","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0042","dso_name"=>"Nawagattegama","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0043","dso_name"=>"Arachchikattuwa","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0044","dso_name"=>"Chilaw","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0045","dso_name"=>"Madampe","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0046","dso_name"=>"Dankotuwa","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0047","dso_name"=>"Mahawewa","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0048","dso_name"=>"Pallama","district_id"=>"DIS008",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0049","dso_name"=>"Medirigiriya","district_id"=>"DIS006",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0050","dso_name"=>"Elahera","district_id"=>"DIS006",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0051","dso_name"=>"Lankapura","district_id"=>"DIS006",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0052","dso_name"=>"Dimbulagala","district_id"=>"DIS006",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0053","dso_name"=>"Hingurakgoda","district_id"=>"DIS006",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0054","dso_name"=>"Thamankaduwa","district_id"=>"DIS006",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0055","dso_name"=>"Welikanda","district_id"=>"DIS006",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0056","dso_name"=>"Ambagamuwa","district_id"=>"DIS001",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0057","dso_name"=>"Hanguranketha","district_id"=>"DIS001",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0058","dso_name"=>"Kothmale","district_id"=>"DIS001",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0059","dso_name"=>"Nuwara Eliya","district_id"=>"DIS001",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0060","dso_name"=>"Walapane","district_id"=>"DIS001",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0061","dso_name"=>"Tunukkai","district_id"=>"DIS011",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0062","dso_name"=>"Pudukudiyirippu","district_id"=>"DIS011",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0063","dso_name"=>"Maritimepattu","district_id"=>"DIS011",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0064","dso_name"=>"Mathai East","district_id"=>"DIS011",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0065","dso_name"=>"Wellawaya","district_id"=>"DIS024",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0066","dso_name"=>"Thanamalwila","district_id"=>"DIS024",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0067","dso_name"=>"Siyambalanduwa","district_id"=>"DIS024",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0068","dso_name"=>"Sewanagala","district_id"=>"DIS024",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0069","dso_name"=>"Moneragala","district_id"=>"DIS024",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0070","dso_name"=>"Medagama","district_id"=>"DIS024",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0071","dso_name"=>"Katharagama","district_id"=>"DIS024",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0072","dso_name"=>"Madulla","district_id"=>"DIS024",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0073","dso_name"=>"Buttala","district_id"=>"DIS024",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0074","dso_name"=>"Bibila","district_id"=>"DIS024",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0075","dso_name"=>"Badalkumbura","district_id"=>"DIS024",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0076","dso_name"=>"Kotapola","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0077","dso_name"=>"Pasgoda","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0078","dso_name"=>"Pitabeddara","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0079","dso_name"=>"Mulatiyana","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0080","dso_name"=>"Akuressa","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0081","dso_name"=>"Athuraliya","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0082","dso_name"=>"Hakmana","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0083","dso_name"=>"Kamburupitiya","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0084","dso_name"=>"Kirinda Puhulwella","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0085","dso_name"=>"Malimbada","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0086","dso_name"=>"Welipitiya","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0087","dso_name"=>"Thihagoda","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0088","dso_name"=>"Devinuwara","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0089","dso_name"=>"Dickwella","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0090","dso_name"=>"Weligama","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0091","dso_name"=>"Matara Four Gravets","district_id"=>"DIS017",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0092","dso_name"=>"Yatawatta","district_id"=>"DIS002",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0093","dso_name"=>"Ambanganga Koralaya","district_id"=>"DIS002",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0094","dso_name"=>"Dambulla","district_id"=>"DIS002",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0095","dso_name"=>"Wilgamuwa","district_id"=>"DIS002",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0096","dso_name"=>"Matale","district_id"=>"DIS002",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0097","dso_name"=>"Laggala-Pallegama","district_id"=>"DIS002",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0098","dso_name"=>"Naula","district_id"=>"DIS002",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0099","dso_name"=>"Pallepola","district_id"=>"DIS002",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0100","dso_name"=>"Galewela","district_id"=>"DIS002",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0101","dso_name"=>"Rattota","district_id"=>"DIS002",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0102","dso_name"=>"Ukuwela","district_id"=>"DIS002",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0103","dso_name"=>"Mannar Town","district_id"=>"DIS012",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0104","dso_name"=>"Manthai West","district_id"=>"DIS012",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0105","dso_name"=>"Musalai","district_id"=>"DIS012",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0106","dso_name"=>"Madhu","district_id"=>"DIS012",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0107","dso_name"=>"Nanaddan","district_id"=>"DIS012",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0108","dso_name"=>"Giribawa","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0109","dso_name"=>"Galgamuwa","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0110","dso_name"=>"Ehetuwewa","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0111","dso_name"=>"Ambanpola","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0112","dso_name"=>"Polpithigama","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0113","dso_name"=>"Kotawehera","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0114","dso_name"=>"Ganewatta","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0115","dso_name"=>"Ibbagamuwa","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0116","dso_name"=>"Mahawa","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0117","dso_name"=>"Kurunegala","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0118","dso_name"=>"Nikaweratiya","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0119","dso_name"=>"Pannala","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0120","dso_name"=>"Udubaddawa","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0121","dso_name"=>"Bingiriya","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0122","dso_name"=>"Kuliyapitiya West","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0123","dso_name"=>"Kuliyapitiya East","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0124","dso_name"=>"Rasnayakapura","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0125","dso_name"=>"Weerambugedara","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0126","dso_name"=>"Alawwa","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0127","dso_name"=>"Narammala","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0128","dso_name"=>"Bamunukotuwa","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0129","dso_name"=>"Katupotha","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0130","dso_name"=>"Panduwasnuwara","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0131","dso_name"=>"Kobeigane","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0132","dso_name"=>"Maspotha","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0133","dso_name"=>"Mallawapitiya","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0134","dso_name"=>"Rideegama","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0135","dso_name"=>"Wariyapola","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0136","dso_name"=>"Mawathagama","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0137","dso_name"=>"Polgahawela","district_id"=>"DIS009",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0138","dso_name"=>"Karachchi","district_id"=>"DIS013",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0139","dso_name"=>"Poonakary","district_id"=>"DIS013",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0140","dso_name"=>"Pachchilaipalli","district_id"=>"DIS013",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0141","dso_name"=>"Dehiovita","district_id"=>"DIS016",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0142","dso_name"=>"Ruwanwella","district_id"=>"DIS016",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0143","dso_name"=>"Yatiyanthota","district_id"=>"DIS016",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0144","dso_name"=>"Deraniyagala","district_id"=>"DIS016",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0145","dso_name"=>"Warakapola","district_id"=>"DIS016",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0146","dso_name"=>"Galigamuwa","district_id"=>"DIS016",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0147","dso_name"=>"Bulathkohupitiya","district_id"=>"DIS016",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0148","dso_name"=>"Rambukkana","district_id"=>"DIS016",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0149","dso_name"=>"Kegalle","district_id"=>"DIS016",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0150","dso_name"=>"Mawanella","district_id"=>"DIS016",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0151","dso_name"=>"Aranayaka","district_id"=>"DIS016",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0152","dso_name"=>"Minipe","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0153","dso_name"=>"Udunuwara","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0154","dso_name"=>"Hatharaliyadda","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0155","dso_name"=>"Poojapitiya","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0156","dso_name"=>"Thumpane","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0157","dso_name"=>"Akurana","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0158","dso_name"=>"Ganga Ihala Korale","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0159","dso_name"=>"Udadumbara","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0160","dso_name"=>"Udapalatha","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0161","dso_name"=>"Delthota","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0162","dso_name"=>"Pasbage Korale","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0163","dso_name"=>"Medadumbara","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0164","dso_name"=>"Pathadumbara","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0165","dso_name"=>"Panwila","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0166","dso_name"=>"Harispattuwa","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0167","dso_name"=>"Yatinuwara","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0168","dso_name"=>"Doluwa","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0169","dso_name"=>"Pathahewaheta","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0170","dso_name"=>"Kundasale","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0171","dso_name"=>"Gangawata Korale","district_id"=>"DIS003",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0172","dso_name"=>"Panadura","district_id"=>"DIS021",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0173","dso_name"=>"Horana","district_id"=>"DIS021",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0174","dso_name"=>"Ingiriya","district_id"=>"DIS021",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0175","dso_name"=>"Agalawatta","district_id"=>"DIS021",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0176","dso_name"=>"Walallawita","district_id"=>"DIS021",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0177","dso_name"=>"Palindanuwara","district_id"=>"DIS021",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0178","dso_name"=>"Mathugama","district_id"=>"DIS021",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0179","dso_name"=>"Beruwala","district_id"=>"DIS021",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0180","dso_name"=>"Bulathsinhala","district_id"=>"DIS021",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0181","dso_name"=>"Dodangoda","district_id"=>"DIS021",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0182","dso_name"=>"Millaniya","district_id"=>"DIS021",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0183","dso_name"=>"Bandaragama","district_id"=>"DIS021",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0184","dso_name"=>"Kaluthara","district_id"=>"DIS021",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0185","dso_name"=>"Madurawala","district_id"=>"DIS021",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0186","dso_name"=>"Chankanai","district_id"=>"DIS014",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0187","dso_name"=>"Sandilipay","district_id"=>"DIS014",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0188","dso_name"=>"Tellipallai","district_id"=>"DIS014",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0189","dso_name"=>"Uduvil","district_id"=>"DIS014",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0190","dso_name"=>"Nallur","district_id"=>"DIS014",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0191","dso_name"=>"Jaffna","district_id"=>"DIS014",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0192","dso_name"=>"Kopay","district_id"=>"DIS014",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0193","dso_name"=>"Velanai","district_id"=>"DIS014",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0194","dso_name"=>"Kayts","district_id"=>"DIS014",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0195","dso_name"=>"Point Pedro","district_id"=>"DIS014",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0196","dso_name"=>"Karaveddy","district_id"=>"DIS014",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0197","dso_name"=>"Chavakachcheri","district_id"=>"DIS014",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0198","dso_name"=>"Delft","district_id"=>"DIS014",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0199","dso_name"=>"Maruthnkerny","district_id"=>"DIS014",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0200","dso_name"=>"Tangalle","district_id"=>"DIS018",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0201","dso_name"=>"Ambalantota","district_id"=>"DIS018",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0202","dso_name"=>"Weeraketiya","district_id"=>"DIS018",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0203","dso_name"=>"Walasmulla","district_id"=>"DIS018",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0204","dso_name"=>"Katuwana","district_id"=>"DIS018",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0205","dso_name"=>"Angunukolapelessa","district_id"=>"DIS018",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0206","dso_name"=>"Okewela","district_id"=>"DIS018",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0207","dso_name"=>"Beliatta","district_id"=>"DIS018",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0208","dso_name"=>"Tissamaharama","district_id"=>"DIS018",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0209","dso_name"=>"Lunugamvehera","district_id"=>"DIS018",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0210","dso_name"=>"Sooriyawewa","district_id"=>"DIS018",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0211","dso_name"=>"Hambantota","district_id"=>"DIS018",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0212","dso_name"=>"Wattala","district_id"=>"DIS022",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0213","dso_name"=>"Kelaniya","district_id"=>"DIS022",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0214","dso_name"=>"Mahara","district_id"=>"DIS022",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0215","dso_name"=>"Biyagama","district_id"=>"DIS022",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0216","dso_name"=>"Dompe","district_id"=>"DIS022",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0217","dso_name"=>"Attanagalla","district_id"=>"DIS022",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0218","dso_name"=>"Gampaha","district_id"=>"DIS022",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0219","dso_name"=>"Minuwangoda","district_id"=>"DIS022",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0220","dso_name"=>"Divulapitiya","district_id"=>"DIS022",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0221","dso_name"=>"Mirigama","district_id"=>"DIS022",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0222","dso_name"=>"Katana","district_id"=>"DIS022",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0223","dso_name"=>"Ja-Ela","district_id"=>"DIS022",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0224","dso_name"=>"Negombo","district_id"=>"DIS022",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0225","dso_name"=>"Akmeemana","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0226","dso_name"=>"Ambalangoda","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0227","dso_name"=>"Baddegama","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0228","dso_name"=>"Balapitiya","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0229","dso_name"=>"Bentota","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0230","dso_name"=>"Bope-Poddala","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0231","dso_name"=>"Elpitiya","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0232","dso_name"=>"Galle Four Gravets","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0233","dso_name"=>"Habaraduwa","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0234","dso_name"=>"Hikkaduwa","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0235","dso_name"=>"Karandeniya","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0236","dso_name"=>"Nagoda","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0237","dso_name"=>"Neluwa","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0238","dso_name"=>"Niyagama","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0239","dso_name"=>"Thawalama","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0240","dso_name"=>"Welivitiya-Divithura","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0241","dso_name"=>"Yakkalamulla","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0242","dso_name"=>"Imaduwa","district_id"=>"DIS019",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0243","dso_name"=>"Padukka","district_id"=>"DIS023",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0244","dso_name"=>"Homagama","district_id"=>"DIS023",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0245","dso_name"=>"Hanwella","district_id"=>"DIS023",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0246","dso_name"=>"Dehiwala","district_id"=>"DIS023",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0247","dso_name"=>"Kesbewa","district_id"=>"DIS023",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0248","dso_name"=>"Maharagama","district_id"=>"DIS023",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0249","dso_name"=>"Kolonnawa","district_id"=>"DIS023",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0250","dso_name"=>"Colombo","district_id"=>"DIS023",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0251","dso_name"=>"Rathmalana","district_id"=>"DIS023",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0252","dso_name"=>"Moratuwa","district_id"=>"DIS023",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0253","dso_name"=>"Thimbirigasyaya","district_id"=>"DIS023",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0254","dso_name"=>"Sri Jayawardanapura Kotte","district_id"=>"DIS023",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0255","dso_name"=>"Kaduwela","district_id"=>"DIS023",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0256","dso_name"=>"Koralai Pattu (Valach.)","district_id"=>"DIS005",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0257","dso_name"=>"Koralai P. W. (Oddamavadi)","district_id"=>"DIS005",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0258","dso_name"=>"Manmunai S. and Eruvilpattu","district_id"=>"DIS005",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0259","dso_name"=>"Koralai Pattu North","district_id"=>"DIS005",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0260","dso_name"=>"Manmunai North","district_id"=>"DIS005",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0261","dso_name"=>"Manmunai West","district_id"=>"DIS005",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0262","dso_name"=>"Manmunai South - West","district_id"=>"DIS005",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0263","dso_name"=>"Porativu Pattu","district_id"=>"DIS005",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0264","dso_name"=>"Manmunai P. (Araipattai)","district_id"=>"DIS005",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0265","dso_name"=>"Eravur Town","district_id"=>"DIS005",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0266","dso_name"=>"Eravur Pattu","district_id"=>"DIS005",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0267","dso_name"=>"Kattankudy","district_id"=>"DIS005",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0268","dso_name"=>"Soranathota","district_id"=>"DIS020",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0269","dso_name"=>"Haldummulla","district_id"=>"DIS020",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0270","dso_name"=>"Kandaketiya","district_id"=>"DIS020",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0271","dso_name"=>"Mahiyanganaya","district_id"=>"DIS020",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0272","dso_name"=>"Rideemaliyadda","district_id"=>"DIS020",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0273","dso_name"=>"Welimada","district_id"=>"DIS020",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0274","dso_name"=>"Haputhale","district_id"=>"DIS020",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0275","dso_name"=>"Passara","district_id"=>"DIS020",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0276","dso_name"=>"Meegahakivula","district_id"=>"DIS020",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0277","dso_name"=>"Uva Paranagama","district_id"=>"DIS020",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0278","dso_name"=>"Hali Ela","district_id"=>"DIS020",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0279","dso_name"=>"Badulla","district_id"=>"DIS020",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0280","dso_name"=>"Ella","district_id"=>"DIS020",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0281","dso_name"=>"Bandarawela","district_id"=>"DIS020",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0282","dso_name"=>"Lunugala","district_id"=>"DIS020",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0283","dso_name"=>"Thambuttegama","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0284","dso_name"=>"Horowpothana","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0285","dso_name"=>"Maha Vilachchiya","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0286","dso_name"=>"Padaviya","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0287","dso_name"=>"Galenbidunuwawe","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0288","dso_name"=>"Galnewa","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0289","dso_name"=>"Ipalogama","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0290","dso_name"=>"Kahatagasdigiliya","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0291","dso_name"=>"Kekirawa","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0292","dso_name"=>"Thirappane","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0293","dso_name"=>"Medawachchiya","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0294","dso_name"=>"Rambewa","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0295","dso_name"=>"Mihintale","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0296","dso_name"=>"Nochchiyagama","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0297","dso_name"=>"Palugaswewa","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0298","dso_name"=>"Palagala","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0299","dso_name"=>"Kebithigollewa","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0300","dso_name"=>"Nuwaragam Palatha East","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0301","dso_name"=>"Thalawa","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0302","dso_name"=>"Rajanganaya","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0303","dso_name"=>"Nachchadoowa","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0304","dso_name"=>"Nuwaragam Palatha Central","district_id"=>"DIS007",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0305","dso_name"=>"Lahugala","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0306","dso_name"=>"Pothuvil","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0307","dso_name"=>"Thirukkovil","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0308","dso_name"=>"Damana","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0309","dso_name"=>"Alayadiwembu","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0310","dso_name"=>"Akkaraipattu","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0311","dso_name"=>"Eragama","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0312","dso_name"=>"Addalachchenai","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0313","dso_name"=>"Ninthavur","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0314","dso_name"=>"Karativu","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0315","dso_name"=>"Sainthamarathu","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0316","dso_name"=>"Kalmunai","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0317","dso_name"=>"Samanthurai","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0318","dso_name"=>"Navithanveli","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0319","dso_name"=>"Ampara","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0320","dso_name"=>"Uhana","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0321","dso_name"=>"Mahaoya","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0322","dso_name"=>"Padiyathalawa","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
            array("dso_id"=>"DSO0323","dso_name"=>"Dehiattakandiya","district_id"=>"DIS025",'created_at' => Carbon::now()->format('Y-m-d H:i:s'),'updated_at' => Carbon::now()->format('Y-m-d H:i:s')),
        ]);
    }
}
